//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDN
    {
        public string MaHDN { get; set; }
        public string MaMH { get; set; }
        public int SoLg { get; set; }
    
        public virtual tblHoaDonNhap tblHoaDonNhap { get; set; }
        public virtual tblMatHang tblMatHang { get; set; }
    }
}
