//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDonNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDonNhap()
        {
            this.tblChiTietHDNs = new HashSet<tblChiTietHDN>();
        }
    
        public string MaHDN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDN> tblChiTietHDNs { get; set; }
        public virtual tblNCC tblNCC { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
