//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMatHang()
        {
            this.tblChiTietHDBs = new HashSet<tblChiTietHDB>();
            this.tblChiTietHDNs = new HashSet<tblChiTietHDN>();
        }
    
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public string Mota { get; set; }
        public string LinkHinhAnh { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public string MaLoai { get; set; }
        public string MaKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDB> tblChiTietHDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDN> tblChiTietHDNs { get; set; }
        public virtual tblKhuyenMai tblKhuyenMai { get; set; }
        public virtual tblLoaiHang tblLoaiHang { get; set; }
    }
}
