//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVoucher()
        {
            this.tblApDungVouchers = new HashSet<tblApDungVoucher>();
            this.tblSoHuuVouchers = new HashSet<tblSoHuuVoucher>();
        }
    
        public string MaV { get; set; }
        public string TenV { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> GTToiThieu { get; set; }
        public Nullable<int> GTToiDa { get; set; }
        public Nullable<int> Loai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApDungVoucher> tblApDungVouchers { get; set; }
        public virtual tblDonVi tblDonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSoHuuVoucher> tblSoHuuVouchers { get; set; }
    }
}
